N_S: 2
N_T: 8
batch_size: 2
batch_size_vali: 4
eval_period: !!python/tuple
- 20160101
- 20201231
full_data_path:
  max: data/max_values.npy
  min: data/min_values.npy
  sic: data/sic_path.txt
  siv_u: data/siv_u_path.txt
  siv_v: data/siv_v_path.txt
  t2m: data/t2m_path.txt
  u10: data/u10_path.txt
  v10: data/v10_path.txt
hid_S: 64
hid_T: 512
img_size: !!python/tuple
- 448
- 304
input_dim: 6
input_gap: 1
input_length: 7
lr: 1.0e-05
model: SimVP
num_epochs: 300
num_workers: 32
patience: 30
pred_gap: 1
pred_length: 7
pred_shift: 7
spatio_kernel_dec: 3
spatio_kernel_enc: 3
test_results_path: test_results
train_log_path: train_logs
train_period: !!python/tuple
- 19790101
- 20151231
