# Generated by Django 5.0.9 on 2024-12-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadPredictTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('input_files', models.JSONField(blank=True, default=list)),
                ('result_urls', models.JSONField(blank=True, default=list)),
                ('input_times', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', '手动创建'), ('SCHEDULED', '定时任务'), ('API', 'API调用')], default='MANUAL', help_text='标识任务的创建来源', max_length=50)),
            ],
        ),
    ]
