# Generated by Django 5.0.9 on 2024-11-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadpredicttask',
            name='task_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20),
        ),
    ]
