# Generated by Django 5.0.9 on 2024-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaice', '0003_downloadpredicttask_input_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadpredicttask',
            name='source',
            field=models.CharField(choices=[('MANUAL', '手动创建'), ('SCHEDULED', '定时任务'), ('API', 'API调用')], default='MANUAL', help_text='标识任务的创建来源', max_length=50),
        ),
    ]
