# Generated by Django 5.0.8 on 2025-03-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seaice', '0003_modelinterpretertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicgradtask',
            name='x1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dynamicgradtask',
            name='x2',
            field=models.IntegerField(default=432),
        ),
        migrations.AddField(
            model_name='dynamicgradtask',
            name='y1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dynamicgradtask',
            name='y2',
            field=models.IntegerField(default=432),
        ),
    ]
