# Generated by Django 5.0.9 on 2024-11-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaice', '0004_downloadpredicttask_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadpredicttask',
            name='input_times',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
