# Generated by Django 5.0.8 on 2025-04-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seaice', '0005_downloadpredictglobetask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelinterpretertask',
            old_name='grad_day',
            new_name='pred_gap',
        ),
        migrations.AddField(
            model_name='modelinterpretertask',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelinterpretertask',
            name='variable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
